:zap: format, lint, typecheck適用
mypyが型対応していないライブラリのエラー詳細
```
pong/settings.py:15: error: Skipping analyzing "environ": module is installed, but missing library stubs or py.typed marker  [import-untyped]
pong/settings.py:15: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

>  If you are getting a `Skipping analyzing X: module is installed, but missing library stubs or py.typed marker`, error, this means mypy was able to find the module you were importing, but no corresponding type hints.

> Mypy will not try inferring the types of any 3rd party libraries you have installed unless they either have declared themselves to be [PEP 561 compliant stub package](https://mypy.readthedocs.io/en/stable/installed_packages.html#installed-packages) (e.g. with a `py.typed` file) or have registered themselves on [typeshed](https://github.com/python/typeshed), the repository of types for the standard library and some 3rd party libraries

https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker